### ISSUE TITLE
MPEG not supported

### ISSUE THREAD

**Issue by Starwer** [mono/taglib-sharp#104]
When reading an MPG file which ends by a `TagLib.Mpeg.Marker.PaddingPacket` (0xBE), the `TagLib.File.Create()`  factory method just throws an exception. 

A video to reproduce this issue can be downloaded at: https://files.scene.org/view/parties/2006/demozone06/anim/unclear_throat.mpg

**Comment by Starwer** [comment]
[Edit: changed issue title]
Digging deeper: I cannot open any mpg/mpeg file with TagLib# without hitting the `CorruptFileException` exception. I've also tried some files that are even older than the code of the MPEG code (almost unchanged since the legendary @bnickel wrote it). 

every times it gets to the same flow: the `TagLib.Mpeg.File.RFindMarker` is called and look up for the mysterious `Marker.SystemSyncPacket` and fails to find it, issuing a `CorruptFileException`. Because none of the MPEG files I have seen contains such a tag. It makes me wonder if anyone has managed to get this code working on a random MPEG file.

Again I'm willing to make it work, but I'd appreciate some help.

**Comment by bnickel** [comment]
***Disclaimer: I'm not in any way involved with the project and probably won't be much help.  Most of what I'm saying is off memory.***

That's curious.  The pattern we're looking for in RFindMarker is `00 00 01 ba`.  If I do a hex dump of unclear_throat, I can find one near the end at file position 7fd0000.  I'm not sure why RFind would fail here unless there's a bug maybe a long lingering bug in RFind or ByteVector.Find.  A full stack trace would probably help.

For context as to what the system sync packet marker is, MPEG is a streaming format, meaning that we should be able to jump into any part of a stream and be able to start consuming its content, without requiring any knowledge of what happened before in the file.  (This isn't strictly true, I don't think, which is why sometimes when starting a video stream you get green or unrendered areas where old stream content was expected.)  In order for this to work, there need to be clear markers in the stream denoting where packets are.  That way, if we just jumped in in the middle of a packet, we can wait for the marker and start streaming from there.  That's what SystemSyncPacket is.  It's impossible for a MPEG file to exist without them, so if we can't find one we have to consider it corrupt or at least some other format.

Fun fact: The ID3 tagging format had an issue where it would accidentally produce that bit pattern when representing the number 442, causing tags to be read as MPEG data, which lead to the concept of unsynchronized tags and integers to eliminate audio and video glitches.

**Comment by Starwer** [comment]
@bnickel : Thanks a lot for this ! I really appreciate that you reply on a code that you don't control anymore, and after so many years. Your name figures on most of the files so you had quite an impact on this project, whatever was your originating involvment.
Your explanation is a great help to me for understanding the MPEG in general. This also makes the problem clear now. TagLib looks backward in the last 128 bytes for the sync packet. For most of the files (all the MPEGs I have), this is not wide enough. As I have no clue what would be the proper theoretical limit to look up for the las Sync packet I think I rewrite it so that it is limitless.

**Comment by Starwer** [comment]
@bnickel : Thanks to your support, I was able to fix the MPEG support in TagLib#. Thanks again for the help !

**Comment by decriptor** [comment]
Fixed here: https://github.com/mono/taglib-sharp/pull/108
