### ISSUE TITLE
MSBUILD now hardcoded?

### ISSUE THREAD

**Issue by nicman23** [mono/taglib-sharp#139]
there was a massive update and now the project only supports msbuild?

can we please have the option of using mcs back?

**Comment by nicman23** [comment]
yeah on top of that, make install does not install the dlls

old ver (60e7588b53868a2b37dd0bc92868b740da2eeded installs them correctly

**Comment by decriptor** [comment]
What distro are you building on?
What version of mono are you using?

I'll have to look at the make install. I'll add that to the release issue.

**Comment by nicman23** [comment]
arch, msbuild is hardcoded in build/msbuild.include

**Comment by decriptor** [comment]
right, I theory you should be able to change that to xbuild as well and have it still work. Under the hood it is still having mono build everything.

**Comment by decriptor** [comment]
I created an issues for the make install problem #141

**Comment by decriptor** [comment]
I'm going to close since this I've decided to completely delete all of the autotools stuff.

So, moving forward you simply need to grab the source, use either xbuild or msbuild to build the solution.
msbuild /restore TaglibSharp.sln
or
xbuild /restore TaglibSharp.sln (/restore might not work with xbuild, so instead nuget restore)
