### ISSUE TITLE
two nuget packages ?

### ISSUE THREAD

**Issue by John0King** [mono/taglib-sharp#163]
It seems there are two package in nuget
https://www.nuget.org/packages/taglib/  
And 
https://www.nuget.org/packages/TagLibSharp/

**Comment by decriptor** [comment]
This is the one that I created and plan on maintaining - https://www.nuget.org/packages/TagLibSharp/
It has the latest code from master and as soon as can wrap up this release* it'll be a final 2.2 version. For the most part it should be solid.

The other one was created from the last officially released version by the community.

* Due to life and (many) funerals, etc this year I haven't had the time yet to finish this out.
