### ISSUE TITLE
Encoding windows 1251 for tags

### ISSUE THREAD

**Issue by VicLo2020** [mono/taglib-sharp#250]
Hello
How can one get windows-1251 encoding from tags in normal UTF8 form for display?
I get: "Ëó÷øèå ïåñíè" instead "Лучшие песни"

**Comment by Vasilich** [comment]
1. UTF8 isn't "normal" for .NET world.
2. where do you get this string? from what tag?
E.g. ID3v1 assumes Latin1 as encoding, and you can simply convert it to unicode (or UTF8, if you want) using function:
`		// converts string from ID3v1, converted to unicode from 1-byte encoding and
		// interpreted as Latin1 (hardcoded in TagLib/Id3v1/StringHandler.cs),
		// to unicode, using given encoding.
		private static string ConvertStringFromLatin1ToGivenEncoding(string src, Encoding encoding)
		{
			if (src == null) return null;
			//var l = Encoding.Convert(Encoding.Unicode, Encoding.GetEncoding("latin1"), Encoding.Unicode.GetBytes(src));
			var l = Encoding.Convert(Encoding.Unicode, Encoding.Default, Encoding.Unicode.GetBytes(src));
			var a = Encoding.Convert(encoding, Encoding.Unicode, l);
			return Encoding.Unicode.GetString(a);
		}
`

**Comment by VicLo2020** [comment]
I took this composition - https://yadi.sk/d/zJ-lMWT4cWFbkw
and got the result as indicated above.

**Comment by Vasilich** [comment]
1. The encoding in this file in ID3v2 tag is totally wrong, as it uses win1251, but marks fields with encoding "Latin1".
2. it is highly uncommon, that ID3v2.3 tags use Latin1 for string fields containing artist, album or title - default is to use UTF16.
![id3v2_wrong_enc](https://user-images.githubusercontent.com/1168434/107918615-4df43a80-6f6a-11eb-954b-d10defe736f4.png)

So either you need to correct the tags in this file to have proper encoding, or (if you have lot of files with such wrong encoding), you can try the function i posted above, but uncomment 1st line of it, and comment second one:
```C#
		private static string ConvertStringFromLatin1ToGivenEncoding(string src, Encoding encoding)
		{
			if (src == null) return null;
			var l = Encoding.Convert(Encoding.Unicode, Encoding.GetEncoding("latin1"), Encoding.Unicode.GetBytes(src));
			//var l = Encoding.Convert(Encoding.Unicode, Encoding.Default, Encoding.Unicode.GetBytes(src));
			var a = Encoding.Convert(encoding, Encoding.Unicode, l);
			return Encoding.Unicode.GetString(a);
		}
```
and give as second parameter Encoding.GetEncoding("windows-1251").
You can also set `ByteVector.UseBrokenLatin1Behavior = true; // use default encoding instead of Latin1 for ID3v1` for you if your language for non-unicode is set to codepage, that is common for such files (e.g. w1251 :) )
